[package]
name = "node-rs-crc32"
version = "0.1.0"
authors = ["LongYinan <lynweklm@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi-rs = { version = "0.2", path = "../../../napi-rs/napi" }
crc32c = "0.4"

[build-dependencies]
napi-build = { version = "0.1", path = "../../../napi-rs/build" }
